src/main/java/com/raupach/models/User.java
package com.raupach.models;

import java.util.ArrayList;
import java.util.Date;

import com.google.appengine.api.datastore.DatastoreService;
import com.google.appengine.api.datastore.DatastoreServiceFactory;
import com.google.appengine.api.datastore.Entity;
import com.google.appengine.api.datastore.EntityNotFoundException;
import com.google.appengine.api.datastore.Key;
import com.google.appengine.api.datastore.KeyFactory;


/* 
 * The User model handle the storage of User data and the creation of the User model objects
 */

public class User {
	private String id;					// user id, created in Facebook
	private String firstName;			// First name 
	private String lastName;			// Last name
	private String emailAddress;		// email address
	private Date lastUsed;				// not used in the end
	
	
	// ceates and stores a user from Facebook
	public User(String id, String firstName, String lastName, String emailAddress) {
		super();
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.emailAddress = emailAddress;
		this.lastUsed = new Date();
		save();
	}
	
	// Loads a user from storage
	public User(String id) throws EntityNotFoundException {
		super();
		this.id = id;
		load();
	}


	// saves a users properies to storage
	private void save() {
		
		DatastoreService ds = DatastoreServiceFactory.getDatastoreService();
		
		// Create the user entity
		Entity user = new Entity("User", this.id);
		user.setProperty("firstName", this.firstName);
		user.setProperty("lastName", this.lastName);
		user.setProperty("emailAddress", this.emailAddress);
		user.setProperty("lastUsed", this.lastUsed);
		// store it in the database
		ds.put(user);
		
	}
	
	// loads a user from storage
	private void load() throws EntityNotFoundException {
		// get the user from storage 
		DatastoreService datastore = DatastoreServiceFactory.getDatastoreService();
		Key k = KeyFactory.createKey("User", this.id); 
		Entity storedUser = datastore.get(k);
		
		// load in the user's properies
		this.firstName = (String) storedUser.getProperty("firstName");
		this.lastName = (String) storedUser.getProperty("lastName");
		this.emailAddress = (String) storedUser.getProperty("emailAddress");
		this.lastUsed = (Date) storedUser.getProperty("lastUsed");
		
		
	}

	//	getters and setters 
	
	// Returns all the tweets for this user
	public  ArrayList<Tweet> getTweets() {
		 return Tweet.usersTweets(this.id, true);
	}
	
	// returns the user's full name
	public String getFullName() {
		return firstName + " " + lastName;
	}
	
	public String getFirstName() {
		return firstName;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public Date getLastUsed() {
		return lastUsed;
	}
	public void setLastUsed(Date lastUsed) {
		this.lastUsed = lastUsed;
	}
	
	public String getEmailAddress() {
		return emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}
	
}

src/main/java/com/raupach/FriendsServlet.java
package com.raupach;

import java.io.IOException;
import java.util.ArrayList;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.google.appengine.api.datastore.EntityNotFoundException;
import com.raupach.models.User;

@WebServlet(
    name = "FriendsServlet",
    urlPatterns = {"/friends"}
)


/* 
 * The Friend Servlet take the friends request and collects all the 
 * friend user objects in an array and hands them to the friends.jsp 
 * view.
 */

public class FriendsServlet extends HttpServlet {

  @Override
  public void doGet(HttpServletRequest request, HttpServletResponse response) 
      throws IOException {
	  
	// take the passed in friend user ids and split them into an array 
	String [] friend_ids = request.getParameter("friends").split(",");  
	ArrayList<User> friends = new ArrayList<User>();  
	
	// loop through the friend ids and collect the user objects
	for (String friend_id: friend_ids) {
		try {
			friends.add(new User(friend_id));
		} catch (EntityNotFoundException e) {
			// if the friend doesn't exist skip it
		}
	}
	
	// pass the friends to the friends view
	request.setAttribute("friends", friends);
	try {
		request.getRequestDispatcher("friends.jsp").forward(request, response);
	} catch (ServletException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
	

  }
}

src/main/java/com/raupach/LogInServlet.java
package com.raupach;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet(
    name = "LogInServlet",
    urlPatterns = {"/"}
)

/*
 * The login Servlet is the root of the site.  All it does is call the 
 * login.jsp view.
 */

public class LogInServlet extends HttpServlet {

  @Override
  public void doGet(HttpServletRequest request, HttpServletResponse response) 
      throws IOException {
	  
	doBoth(request, response);
  }

  @Override
  public void doPost(HttpServletRequest request, HttpServletResponse response) 
      throws IOException {
	  
	doBoth(request, response);
  }
  
  
  // Since we want both GET and POST requests to act the same.
  private void doBoth(HttpServletRequest request, HttpServletResponse response) throws IOException {
	try {
		request.getRequestDispatcher("log_in.jsp").forward(request, response);
	} catch (ServletException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
}
}

src/main/java/com/raupach/TopTweetServlet.java
package com.raupach;

import java.io.IOException;
import java.util.ArrayList;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.raupach.models.Tweet;

@WebServlet(
    name = "TopTweetServlet",
    urlPatterns = {"/top-tweets"}
)

/*
 * The Top Tweet Servlet collects all the tweets, in order of popularity
 * and hands them to the top_tweets.jsp view.
 */


public class TopTweetServlet extends HttpServlet {

  @Override
  public void doGet(HttpServletRequest request, HttpServletResponse response) 
      throws IOException {
	  
	// collect the top tweets and hand them to the view
	ArrayList<Tweet> tweets = Tweet.TopTweets();
	
	request.setAttribute("tweets", tweets);
	
	try {
		request.getRequestDispatcher("top_tweets.jsp").forward(request, response);
	} catch (ServletException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}

  }
}

src/main/java/com/raupach/TweetDeleteServlet.java
package com.raupach;

import java.io.IOException;
import java.util.ArrayList;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import com.google.appengine.api.datastore.EntityNotFoundException;
import com.raupach.models.Tweet;
import com.raupach.models.User;

@WebServlet(
    name = "TweetDeleteServlet",
    urlPatterns = {"/tweet/delete"}
)

/*
 * The TweetDeleteServlet takes the request to delete a tweet 
 * deletes the tweet and returns the user the the tweets.jsp view.
 */

public class TweetDeleteServlet extends HttpServlet {

  @Override
  public void doGet(HttpServletRequest request, HttpServletResponse response) 
      throws IOException {
	  
	
	// Get the currently logged in user 
	User user;
	HttpSession session = request.getSession(true);
	try {
		user = new User((String) session.getAttribute("user_id"));
	} catch (EntityNotFoundException e) {
		user = null;
		e.printStackTrace();
	}
	request.setAttribute("user", user);
	
	
	// Delete the requested tweet
	// TODO make sure the tweet belongs to the current user
	Tweet.delete(request.getParameter("tweetID"));
	
	// Collect all the remaining tweets and hand them to the tweet.jsp
	ArrayList<Tweet> tweets = Tweet.usersTweets(user.getId(), false);
	request.setAttribute("tweets", tweets);
	
	try {
		request.getRequestDispatcher("../tweet.jsp").forward(request, response);
	} catch (ServletException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
	

  }
  
}

src/main/java/com/raupach/TweetServlet.java
package com.raupach;

import java.io.IOException;
import java.util.ArrayList;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import com.google.appengine.api.datastore.EntityNotFoundException;
import com.raupach.models.Tweet;
import com.raupach.models.User;

@WebServlet(
    name = "TweetServlet",
    urlPatterns = {"/tweet"}
)

/*
 * The Tweet Servlet 
 *  1) Takes the initial login information and saves the User // this should be moved
 *  2) Collects the user & user's tweets for display
 *  3) Takes the POST of new tweet and saves them. 
 */

public class TweetServlet extends HttpServlet {

  // the get request might be coming from two places
  // the navigation bar or the login screen
  @Override
  public void doGet(HttpServletRequest request, HttpServletResponse response) 
      throws IOException {
	// store the current user in a settion  
	// create a session object if it is already not created.
    HttpSession session = request.getSession(true);
    // get the session id and the param id for latter comparison
	String user_session_id = (String) session.getAttribute("user_id");
	String user_param_id = request.getParameter("userID");
    User user;
    
    // if this is a new session of the session id is null 
    // then we want to create/update and User.
    if (session.isNew() || user_session_id == null ) {
    	 user = new User(
    			 user_param_id,
    			 request.getParameter("first_name"),
    			 request.getParameter("last_name"),
    			 request.getParameter("email_address"));
    	 
    	 // save the new user in the session 
    	 session.setAttribute("user_id", user.getId());
    } else {
    	try {
    		// if there is a session then make sure it matches the session id
    		// if now create/update the current user
    		if (user_param_id != null && !user_session_id.equals(user_param_id )) {
    			user = new User(
    	    			 user_param_id,
    	    			 request.getParameter("first_name"),
    	    			 request.getParameter("last_name"),
    	    			 request.getParameter("email_address"));
    			// save the new user in the session
    			session.setAttribute("user_id", user.getId());
    		} else {
    			// otherwise just load up the session user. Whew
    			user = new User(user_session_id);
    		}
		} catch (EntityNotFoundException e) {
			user = null;
			e.printStackTrace();
		}
    }
	
	request.setAttribute("user", user);
	
	// collect the user's tweets and send them to the view
	ArrayList<Tweet> tweets = Tweet.usersTweets(user.getId(), false);
	request.setAttribute("tweets", tweets);

	try {
		request.getRequestDispatcher("tweet.jsp").forward(request, response);
	} catch (ServletException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
	

  }

  
  // a Post request is a new tweet
@Override
  protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
	
	// get the user id from the session
    HttpSession session = request.getSession(true);
	String user_id = (String) session.getAttribute("user_id");
	
	User user;
	Tweet tweet;
	
	try {
		// get the user
		user = new User(user_id);
		request.setAttribute("user", user);
		
		// get the users tweet before adding the new tweet because 
		// sometime the new tweet will not show up fast enough 
		// so we'll add it ourselves
		ArrayList<Tweet> tweets = Tweet.usersTweets(user.getId(), false);
		request.setAttribute("tweets", tweets);
		
		// create the new tweet and save it.
		tweet = new Tweet(request.getParameter("content"), user.getId(), user.getFullName());
		tweet.save();
		
		// add the new tweet to the top of the tweet list.
		tweets.add(0, tweet);
		
	} catch (EntityNotFoundException e1) {
		e1.printStackTrace();
	}
	
	try {
		request.getRequestDispatcher("tweet.jsp").forward(request, response);
	} catch (ServletException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
}
  
  
}

src/main/java/com/raupach/TweetShowServlet.java
package com.raupach;

import java.io.IOException;
import java.util.ArrayList;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import com.google.appengine.api.datastore.EntityNotFoundException;
import com.raupach.models.Tweet;
import com.raupach.models.User;

@WebServlet(
    name = "TweetShowServlet",
    urlPatterns = {"/tweet/show"}
)

/*
 * The show tweet get a tweet from storage and displays it in the 
 * tweet_show.jsp view.
 */

public class TweetShowServlet extends HttpServlet {

  @Override
  public void doGet(HttpServletRequest request, HttpServletResponse response) 
      throws IOException {
	  
	
	  // get the tweet from storage
	Tweet tweet;
	try {
		tweet = new Tweet(request.getParameter("tweetID"));
	} catch (EntityNotFoundException e1) {
		// TODO Auto-generated catch block
		tweet = null;
		e1.printStackTrace();
	}
	
	// hand the tweet to the view.
	request.setAttribute("tweet", tweet);
	
	try {
		request.getRequestDispatcher("../tweet_show.jsp").forward(request, response);
	} catch (ServletException e) {
		e.printStackTrace();
	}
	

  }
  
}

src/main/webapp/_facebook.jsp
<script>
  window.fbAsyncInit = function() {
	    FB.init({
	        appId      : '105089530374875',
	        xfbml      : true,
	        version    : 'v3.0'
	      });
      
    FB.AppEvents.logPageView();   
      
    FB.getLoginStatus(function(response) {
	   // statusChangeCallback(response);
	});
    
    
    // put a listener on each of the share buttons 
    var classname = document.getElementsByClassName("share_tweet");
    var share_tweet = function(event) {
    	event.preventDefault()
    	
        // Call the faceback share method to share our tweet to to a timeline
        FB.ui({
  		  method: 'share',
  		  href: 'https://facetweet-204615.appspot.com/tweet/show?tweetID=' + this.dataset.id,
  		  quote: this.dataset.content + " --" + this.dataset.author,
  		  app_id: '105089530374875'
  		}, function(response){});
    };

    for (var i = 0; i < classname.length; i++) {
        classname[i].addEventListener('click', share_tweet, false);
    };
    
    
    // put a listener on each of the send buttons 
    var classname = document.getElementsByClassName("send_tweet");
    var send_tweet = function(event) {
    	event.preventDefault()
        
    	// Call the facebook send method to messenge a user with a tweet 
        FB.ui({
  		  method: 'send',
  		  link: 'https://facetweet-204615.appspot.com/tweet/show?tweetID=' + this.dataset.id,
  		  app_id: '105089530374875'
  		}, function(response){});
    };

    for (var i = 0; i < classname.length; i++) {
        classname[i].addEventListener('click', send_tweet, false);
    };
    
    
    // put a listenser on the friends navigation button that collects the user's friends 
    // ids and sends them the the server
    document.getElementById("friends-nav-button").addEventListener("click", function(event){
        event.preventDefault();
        
        // call the facebook friends API method
        FB.api(
        		  '/me/friends',
        		  'GET',
        		  {},
        		  function(response) {
					  // gather the friend ids 
        		      var friends = []
        		      var arrayLength = response.data.length;
        		      for (var i = 0; i < arrayLength; i++) {
        		          friends.push(response.data[i].id);
        		      }
        		      // pass them to the server loading up a new page
        		      window.location.replace("/friends?friends=" + friends);
        		  }
        		);
    });
    
  
  };
  
  
  

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "https://connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
  
  
  

</script>

src/main/webapp/friends.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page import="java.util.ArrayList"%>
<%@page import="com.raupach.models.User" %>
<%@page import="com.raupach.models.Tweet" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Insert title here</title>

<link rel="stylesheet" href="/css/styles.css">
</head>
<body>
	<jsp:include page="_facebook.jsp" />
	<div class="topnav">
  		<a href="/tweet">Tweet</a>
  		<a id="friends-nav-button" class="active" href="/friends">Friends</a>
  		<a href="/top-tweets">Top Tweets</a>
	</div>
	
	
		<div class="tweet-list">
	<% ArrayList<User> friends = (ArrayList<User>) request.getAttribute("friends");
	
	for (User friend : friends) {
	out.print("<h2>" + friend.getFullName() + "</h2>");
	
	ArrayList<Tweet> tweets = (ArrayList<Tweet>) friend.getTweets();
	
	for (Tweet tweet : tweets) {
		out.print("<div class=\"tweet\">");
		out.print("<span class=\"content\">" + tweet.getContent() + "</span> <br>");
		out.print("<span class=\"author\">" + tweet.getUser_name() + "</span> ");
		out.print("<span class=\"timestamp\">" + tweet.getTimestamp() + "</span> <br>");
		out.print("<div class=\"btn-bar\">");
		out.print("<a href=\"/tweet/show?tweetID=" + tweet.getId() + "\">View</a> ");
		out.print("<a data-id=\"" + tweet.getId() + "\" " +  
					 "data-content=\"" + tweet.getContent() + "\" " + 
				     "data-author=\"" + tweet.getUser_name() + "\" " + 
		             "class=\"share_tweet\" href=\"/tweet/show?tweetID=" + tweet.getId() + "\">Share</a> ");
		out.print("<a data-id=\"" + tweet.getId() + "\" " +  
				 "data-content=\"" + tweet.getContent() + "\" " + 
			     "data-author=\"" + tweet.getUser_name() + "\" " + 
	             "class=\"send_tweet\" href=\"/tweet/show?tweetID=" + tweet.getId() + "\">Send</a> ");
	
		out.print("</div></div>");
	}
	}
	%>
	</div>
	
	
	
	
</body>
</html>

src/main/webapp/log_in.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Log-in</title>

<link rel="stylesheet" href="/css/styles.css">
</head>
<body>
	<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '105089530374875',
      cookie     : true,
      xfbml      : true,
      version    : 'v3.0'
    });
      
    FB.AppEvents.logPageView();   
      
    FB.getLoginStatus(function(response) {
	    statusChangeCallback(response);
	});
  
  };
  

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "https://connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
  
  function checkLoginState() {
	  FB.getLoginStatus(function(response) {
	    statusChangeCallback(response);
	  });
	}
  
  
  // if the user is connected then forward them to the tweet page 
  // along with all thier user data we collect from facebook
  function statusChangeCallback(response) {
	  if (response.status == 'connected') {

		  FB.api('/me?fields=first_name,last_name,email', function(data) {
			  var uid = data.id;
			  var first_name = data.first_name;
			  var last_name = data.last_name;
			  var email_address  = data.email;
			  
			  window.location.replace("/tweet?userID=" + uid + 
					  "&first_name=" + first_name +
					  "&last_name=" + last_name +
					  "&email_address=" + email_address);
          });
		  
   		} else {
   			
        }
	}

</script>

<fb:login-button 
  scope="public_profile,email,friends"
  onlogin="checkLoginState();">
</fb:login-button>

</body>
</html>

src/main/webapp/top_tweets.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page import="java.util.ArrayList"%>
<%@page import="com.raupach.models.Tweet" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Top Tweets</title>

<link rel="stylesheet" href="/css/styles.css">
</head>
<body>
	<jsp:include page="_facebook.jsp" />
	<div class="topnav">
  		<a href="/tweet">Tweet</a>
  		<a id="friends-nav-button" href="/friends">Friends</a>
  		<a class="active" href="/top-tweets">Top Tweets</a>
	</div>
	
	<div class="tweet-list">
	<% ArrayList<Tweet> tweets = (ArrayList<Tweet>) request.getAttribute("tweets");
	
	for (Tweet tweet : tweets) {
		out.print("<div class=\"tweet\">");
		out.print("<span class=\"content\">" + tweet.getContent() + "</span> <br>");
		out.print("<span class=\"author\">" + tweet.getUser_name() + "</span> ");
		out.print("<span class=\"timestamp\">" + tweet.getTimestamp() + "</span> <br>");
		out.print("<div class=\"btn-bar\">");
		out.print("<a href=\"/tweet/show?tweetID=" + tweet.getId() + "\">View</a> ");
		out.print("<a data-id=\"" + tweet.getId() + "\" " +  
					 "data-content=\"" + tweet.getContent() + "\" " + 
				     "data-author=\"" + tweet.getUser_name() + "\" " + 
		             "class=\"share_tweet\" href=\"/tweet/show?tweetID=" + tweet.getId() + "\">Share</a> ");
		out.print("<a data-id=\"" + tweet.getId() + "\" " +  
				 "data-content=\"" + tweet.getContent() + "\" " + 
			     "data-author=\"" + tweet.getUser_name() + "\" " + 
	             "class=\"send_tweet\" href=\"/tweet/show?tweetID=" + tweet.getId() + "\">Send</a> ");
	
		out.print("</div></div>");
	}
	
	%>
	</div>

</body>
</html>

src/main/webapp/tweet.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page import="java.util.ArrayList"%>
<%@page import="com.raupach.models.Tweet" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Tweet</title>

<link rel="stylesheet" href="/css/styles.css">

</head>
<body>
	<jsp:include page="_facebook.jsp" />
	<div class="topnav">
  		<a class="active" href="/tweet">Tweet</a>
  		<a id="friends-nav-button" href="/friends">Friends</a>
  		<a href="/top-tweets">Top Tweets</a>
	</div>


	${ user.fullName }
	
	<div>
	<form method="POST" action="/tweet">
		<input id="tweet-field" type="text" name="content">
		<input type="submit" value="Tweet">
		<input type="hidden" name="userID" value="${user.id}">
	</form>
	</div> 
	<div class="tweet-list">
	<% ArrayList<Tweet> tweets = (ArrayList<Tweet>) request.getAttribute("tweets");
	
	for (Tweet tweet : tweets) {
		out.print("<div class=\"tweet\">");
		out.print("<span class=\"content\">" + tweet.getContent() + "</span> <br>");
		out.print("<span class=\"author\">" + tweet.getUser_name() + "</span> ");
		out.print("<span class=\"timestamp\">" + tweet.getTimestamp() + "</span> <br>");
		out.print("<div class=\"btn-bar\">");
		out.print("<a href=\"/tweet/delete?tweetID=" + tweet.getId() + "\">Delete</a> ");
		out.print("<a href=\"/tweet/show?tweetID=" + tweet.getId() + "\">View</a> ");
		//out.print("<a onclick=\"share_tweet(" + tweet.getId() + ", '" + tweet.getContent() + "')\" class=\"share_tweet\" href=\"/tweet/show?tweetID=" + tweet.getId() + "\">Share</a>");
		out.print("<a data-id=\"" + tweet.getId() + "\" " +  
					 "data-content=\"" + tweet.getContent() + "\" " + 
				     "data-author=\"" + tweet.getUser_name() + "\" " + 
		             "class=\"share_tweet\" href=\"/tweet/show?tweetID=" + tweet.getId() + "\">Share</a> ");
		out.print("<a data-id=\"" + tweet.getId() + "\" " +  
				 "data-content=\"" + tweet.getContent() + "\" " + 
			     "data-author=\"" + tweet.getUser_name() + "\" " + 
	             "class=\"send_tweet\" href=\"/tweet/show?tweetID=" + tweet.getId() + "\">Send</a> ");
	
		out.print("</div></div>");
	}
	
	%>
	</div>
</body>
</html>

src/main/webapp/tweet_show.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@page import="java.util.ArrayList"%>
<%@page import="com.raupach.models.Tweet" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">


<meta property="fb:app_id" content="105089530374875">
<meta property="og:type"   content="article" />
<meta property="og:title" content="Tweet by ${ tweet.user_name }">
<meta property="og:description" content="${ tweet.content }">
<meta property="og:image" content="https://s3-us-west-1.amazonaws.com/4pr.solutions/images/bannersaga_cypress_512.png">
<meta property="og:image:width" content="512">
<meta property="og:image:height" content="512">
<title>Tweet by ${ tweet.user_name }</title>

<link rel="stylesheet" href="/css/styles.css">

</head>
<body>
	<jsp:include page="_facebook.jsp" />
	<div class="topnav">
  		<a class="active" href="/tweet">Tweet</a>
  		<a id="friends-nav-button" href="/friends">Friends</a>
  		<a href="/top-tweets">Top Tweets</a>
	</div>
	
	<div class="tweet">
	<span class="content">${ tweet.content } </span> <br>
	<span class="author">${ tweet.user_name } </span> 
	<span class="timestamp">${ tweet.timestamp }</span> <br>
	</div>

	
</body>
</html>